<?php
use Phinx\Seed\AbstractSeed;

class ObjectsTypes extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $this->insert('object_types', [
            ['level'  => 1, 'name'   => 'АО', 'status' => 1],
            ['level'  => 1, 'name'   => 'Аобл', 'status' => 1],
            ['level'  => 1, 'name'   => 'г', 'status' => 1],
            ['level'  => 1, 'name'   => 'край', 'status' => 1],
            ['level'  => 1, 'name'   => 'обл', 'status' => 1],
            ['level'  => 1, 'name'   => 'Респ', 'status' => 1],
            ['level'  => 1, 'name'   => 'Чувашия', 'status' => 1],
            ['level'  => 3, 'name'   => 'АО', 'status' => 1],
            ['level'  => 3, 'name'   => 'г.о.', 'status' => 1],
            ['level'  => 3, 'name'   => 'п', 'status' => 1],
            ['level'  => 3, 'name'   => 'р-н', 'status' => 1],
            ['level'  => 3, 'name'   => 'у', 'status' => 1],
            ['level'  => 4, 'name'   => 'волость', 'status' => 1],
            ['level'  => 4, 'name'   => 'г', 'status' => 1],
            ['level'  => 4, 'name'   => 'г.', 'status' => 1],
            ['level'  => 4, 'name'   => 'дп', 'status' => 1],
            ['level'  => 4, 'name'   => 'массив', 'status' => 1],
            ['level'  => 4, 'name'   => 'п', 'status' => 1],
            ['level'  => 4, 'name'   => 'п/о', 'status' => 1],
            ['level'  => 4, 'name'   => 'пгт', 'status' => 1],
            ['level'  => 4, 'name'   => 'рп', 'status' => 1],
            ['level'  => 4, 'name'   => 'с/а', 'status' => 1],
            ['level'  => 4, 'name'   => 'с/мо', 'status' => 1],
            ['level'  => 4, 'name'   => 'с/о', 'status' => 1],
            ['level'  => 4, 'name'   => 'с/п', 'status' => 1],
            ['level'  => 4, 'name'   => 'с/с', 'status' => 1],
            ['level'  => 4, 'name'   => 'тер', 'status' => 1],
            ['level'  => 5, 'name'   => 'р-н', 'status' => 1],
            ['level'  => 5, 'name'   => 'тер', 'status' => 1],
            ['level'  => 6, 'name'   => 'аал', 'status' => 1],
            ['level'  => 6, 'name'   => 'автодорога', 'status' => 1],
            ['level'  => 6, 'name'   => 'арбан', 'status' => 1],
            ['level'  => 6, 'name'   => 'аул', 'status' => 1],
            ['level'  => 6, 'name'   => 'высел', 'status' => 1],
            ['level'  => 6, 'name'   => 'г', 'status' => 1],
            ['level'  => 6, 'name'   => 'городок', 'status' => 1],
            ['level'  => 6, 'name'   => 'гп', 'status' => 1],
            ['level'  => 6, 'name'   => 'д', 'status' => 1],
            ['level'  => 6, 'name'   => 'дп', 'status' => 1],
            ['level'  => 6, 'name'   => 'ж/д б-ка', 'status' => 1],
            ['level'  => 6, 'name'   => 'ж/д_будка', 'status' => 1],
            ['level'  => 6, 'name'   => 'ж/д_казарм', 'status' => 1],
            ['level'  => 6, 'name'   => 'ж/д_оп', 'status' => 1],
            ['level'  => 6, 'name'   => 'ж/д_платф', 'status' => 1],
            ['level'  => 6, 'name'   => 'ж/д_пост', 'status' => 1],
            ['level'  => 6, 'name'   => 'ж/д_рзд', 'status' => 1],
            ['level'  => 6, 'name'   => 'ж/д_ст', 'status' => 1],
            ['level'  => 6, 'name'   => 'жилзона', 'status' => 1],
            ['level'  => 6, 'name'   => 'жилрайон', 'status' => 1],
            ['level'  => 6, 'name'   => 'заимка', 'status' => 1],
            ['level'  => 6, 'name'   => 'казарма', 'status' => 1],
            ['level'  => 6, 'name'   => 'кв-л', 'status' => 1],
            ['level'  => 6, 'name'   => 'кордон', 'status' => 1],
            ['level'  => 6, 'name'   => 'кп', 'status' => 1],
            ['level'  => 6, 'name'   => 'лпх', 'status' => 1],
            ['level'  => 6, 'name'   => 'м', 'status' => 1],
            ['level'  => 6, 'name'   => 'массив', 'status' => 1],
            ['level'  => 6, 'name'   => 'мкр', 'status' => 1],
            ['level'  => 6, 'name'   => 'нп', 'status' => 1],
            ['level'  => 6, 'name'   => 'остров', 'status' => 1],
            ['level'  => 6, 'name'   => 'п', 'status' => 1],
            ['level'  => 6, 'name'   => 'п/о', 'status' => 1],
            ['level'  => 6, 'name'   => 'п/р', 'status' => 1],
            ['level'  => 6, 'name'   => 'п/ст', 'status' => 1],
            ['level'  => 6, 'name'   => 'пгт', 'status' => 1],
            ['level'  => 6, 'name'   => 'погост', 'status' => 1],
            ['level'  => 6, 'name'   => 'починок', 'status' => 1],
            ['level'  => 6, 'name'   => 'промзона', 'status' => 1],
            ['level'  => 6, 'name'   => 'рзд', 'status' => 1],
            ['level'  => 6, 'name'   => 'рп', 'status' => 1],
            ['level'  => 6, 'name'   => 'с', 'status' => 1],
            ['level'  => 6, 'name'   => 'сл', 'status' => 1],
            ['level'  => 6, 'name'   => 'снт', 'status' => 1],
            ['level'  => 6, 'name'   => 'ст', 'status' => 1],
            ['level'  => 6, 'name'   => 'ст-ца', 'status' => 1],
            ['level'  => 6, 'name'   => 'тер', 'status' => 1],
            ['level'  => 6, 'name'   => 'у', 'status' => 1],
            ['level'  => 6, 'name'   => 'х', 'status' => 1],
            ['level'  => 7, 'name'   => 'а/я', 'status' => 1],
            ['level'  => 7, 'name'   => 'ал.', 'status' => 1],
            ['level'  => 7, 'name'   => 'аллея', 'status' => 1],
            ['level'  => 7, 'name'   => 'б-р', 'status' => 1],
            ['level'  => 7, 'name'   => 'берег', 'status' => 1],
            ['level'  => 7, 'name'   => 'вал', 'status' => 1],
            ['level'  => 7, 'name'   => 'взв.', 'status' => 1],
            ['level'  => 7, 'name'   => 'въезд', 'status' => 1],
            ['level'  => 7, 'name'   => 'городок', 'status' => 1],
            ['level'  => 7, 'name'   => 'гск', 'status' => 1],
            ['level'  => 7, 'name'   => 'д', 'status' => 1],
            ['level'  => 7, 'name'   => 'дор', 'status' => 1],
            ['level'  => 7, 'name'   => 'ж/д_будка', 'status' => 1],
            ['level'  => 7, 'name'   => 'ж/д_казарм', 'status' => 1],
            ['level'  => 7, 'name'   => 'ж/д_оп', 'status' => 1],
            ['level'  => 7, 'name'   => 'ж/д_платф', 'status' => 1],
            ['level'  => 7, 'name'   => 'ж/д_пост', 'status' => 1],
            ['level'  => 7, 'name'   => 'ж/д_рзд', 'status' => 1],
            ['level'  => 7, 'name'   => 'ж/д_ст', 'status' => 1],
            ['level'  => 7, 'name'   => 'жт', 'status' => 1],
            ['level'  => 7, 'name'   => 'заезд', 'status' => 1],
            ['level'  => 7, 'name'   => 'ззд.', 'status' => 1],
            ['level'  => 7, 'name'   => 'зона', 'status' => 1],
            ['level'  => 7, 'name'   => 'к-цо', 'status' => 1],
            ['level'  => 7, 'name'   => 'казарма', 'status' => 1],
            ['level'  => 7, 'name'   => 'кв-л', 'status' => 1],
            ['level'  => 7, 'name'   => 'км', 'status' => 1],
            ['level'  => 7, 'name'   => 'кольцо', 'status' => 1],
            ['level'  => 7, 'name'   => 'коса', 'status' => 1],
            ['level'  => 7, 'name'   => 'линия', 'status' => 1],
            ['level'  => 7, 'name'   => 'лн.', 'status' => 1],
            ['level'  => 7, 'name'   => 'м', 'status' => 1],
            ['level'  => 7, 'name'   => 'мгстр.', 'status' => 1],
            ['level'  => 7, 'name'   => 'местность', 'status' => 1],
            ['level'  => 7, 'name'   => 'мкр', 'status' => 1],
            ['level'  => 7, 'name'   => 'мост', 'status' => 1],
            ['level'  => 7, 'name'   => 'наб', 'status' => 1],
            ['level'  => 7, 'name'   => 'наб.', 'status' => 1],
            ['level'  => 7, 'name'   => 'нп', 'status' => 1],
            ['level'  => 7, 'name'   => 'остров', 'status' => 1],
            ['level'  => 7, 'name'   => 'п', 'status' => 1],
            ['level'  => 7, 'name'   => 'п/о', 'status' => 1],
            ['level'  => 7, 'name'   => 'п/р', 'status' => 1],
            ['level'  => 7, 'name'   => 'п/ст', 'status' => 1],
            ['level'  => 7, 'name'   => 'парк', 'status' => 1],
            ['level'  => 7, 'name'   => 'пер', 'status' => 1],
            ['level'  => 7, 'name'   => 'пер-д', 'status' => 1],
            ['level'  => 7, 'name'   => 'пер.', 'status' => 1],
            ['level'  => 7, 'name'   => 'переезд', 'status' => 1],
            ['level'  => 7, 'name'   => 'пл', 'status' => 1],
            ['level'  => 7, 'name'   => 'пл-ка', 'status' => 1],
            ['level'  => 7, 'name'   => 'платф', 'status' => 1],
            ['level'  => 7, 'name'   => 'пр-д', 'status' => 1],
            ['level'  => 7, 'name'   => 'пр-к', 'status' => 1],
            ['level'  => 7, 'name'   => 'пр-ка', 'status' => 1],
            ['level'  => 7, 'name'   => 'пр-кт', 'status' => 1],
            ['level'  => 7, 'name'   => 'пр-лок', 'status' => 1],
            ['level'  => 7, 'name'   => 'проезд', 'status' => 1],
            ['level'  => 7, 'name'   => 'промзона', 'status' => 1],
            ['level'  => 7, 'name'   => 'просек', 'status' => 1],
            ['level'  => 7, 'name'   => 'просека', 'status' => 1],
            ['level'  => 7, 'name'   => 'проселок', 'status' => 1],
            ['level'  => 7, 'name'   => 'проул.', 'status' => 1],
            ['level'  => 7, 'name'   => 'проулок', 'status' => 1],
            ['level'  => 7, 'name'   => 'рзд', 'status' => 1],
            ['level'  => 7, 'name'   => 'рзд.', 'status' => 1],
            ['level'  => 7, 'name'   => 'ряд', 'status' => 1],
            ['level'  => 7, 'name'   => 'ряды', 'status' => 1],
            ['level'  => 7, 'name'   => 'с', 'status' => 1],
            ['level'  => 7, 'name'   => 'с-к', 'status' => 1],
            ['level'  => 7, 'name'   => 'с-р', 'status' => 1],
            ['level'  => 7, 'name'   => 'с/т', 'status' => 1],
            ['level'  => 7, 'name'   => 'сад', 'status' => 1],
            ['level'  => 7, 'name'   => 'сзд.', 'status' => 1],
            ['level'  => 7, 'name'   => 'сквер', 'status' => 1],
            ['level'  => 7, 'name'   => 'сл', 'status' => 1],
            ['level'  => 7, 'name'   => 'снт', 'status' => 1],
            ['level'  => 7, 'name'   => 'спуск', 'status' => 1],
            ['level'  => 7, 'name'   => 'ст', 'status' => 1],
            ['level'  => 7, 'name'   => 'стр', 'status' => 1],
            ['level'  => 7, 'name'   => 'тер', 'status' => 1],
            ['level'  => 7, 'name'   => 'тер. СНТ', 'status' => 1],
            ['level'  => 7, 'name'   => 'тракт', 'status' => 1],
            ['level'  => 7, 'name'   => 'туп', 'status' => 1],
            ['level'  => 7, 'name'   => 'ул', 'status' => 1],
            ['level'  => 7, 'name'   => 'ул.', 'status' => 1],
            ['level'  => 7, 'name'   => 'уч-к', 'status' => 1],
            ['level'  => 7, 'name'   => 'ф/х', 'status' => 1],
            ['level'  => 7, 'name'   => 'ферма', 'status' => 1],
            ['level'  => 7, 'name'   => 'х', 'status' => 1],
            ['level'  => 7, 'name'   => 'ш', 'status' => 1],
            ['level'  => 7, 'name'   => 'ш.', 'status' => 1],
            ['level'  => 65, 'name'   => 'а/я', 'status' => 1],
            ['level'  => 65, 'name'   => 'ал.', 'status' => 1],
            ['level'  => 65, 'name'   => 'б-г', 'status' => 1],
            ['level'  => 65, 'name'   => 'г-к', 'status' => 1],
            ['level'  => 65, 'name'   => 'гск', 'status' => 1],
            ['level'  => 65, 'name'   => 'днп', 'status' => 1],
            ['level'  => 65, 'name'   => 'дор.', 'status' => 1],
            ['level'  => 65, 'name'   => 'ж/р', 'status' => 1],
            ['level'  => 65, 'name'   => 'зона', 'status' => 1],
            ['level'  => 65, 'name'   => 'кв-л', 'status' => 1],
            ['level'  => 65, 'name'   => 'км', 'status' => 1],
            ['level'  => 65, 'name'   => 'м-ко', 'status' => 1],
            ['level'  => 65, 'name'   => 'местность', 'status' => 1],
            ['level'  => 65, 'name'   => 'месторожд.', 'status' => 1],
            ['level'  => 65, 'name'   => 'мкр', 'status' => 1],
            ['level'  => 65, 'name'   => 'мкр.', 'status' => 1],
            ['level'  => 65, 'name'   => 'н/п', 'status' => 1],
            ['level'  => 65, 'name'   => 'наб.', 'status' => 1],
            ['level'  => 65, 'name'   => 'ост-в', 'status' => 1],
            ['level'  => 65, 'name'   => 'п.', 'status' => 1],
            ['level'  => 65, 'name'   => 'п/р', 'status' => 1],
            ['level'  => 65, 'name'   => 'парк', 'status' => 1],
            ['level'  => 65, 'name'   => 'пер.', 'status' => 1],
            ['level'  => 65, 'name'   => 'пл-ка', 'status' => 1],
            ['level'  => 65, 'name'   => 'пл.', 'status' => 1],
            ['level'  => 65, 'name'   => 'платф.', 'status' => 1],
            ['level'  => 65, 'name'   => 'пр-д', 'status' => 1],
            ['level'  => 65, 'name'   => 'промзона', 'status' => 1],
            ['level'  => 65, 'name'   => 'р-н', 'status' => 1],
            ['level'  => 65, 'name'   => 'с-р', 'status' => 1],
            ['level'  => 65, 'name'   => 'сад', 'status' => 1],
            ['level'  => 65, 'name'   => 'сквер', 'status' => 1],
            ['level'  => 65, 'name'   => 'снт', 'status' => 1],
            ['level'  => 65, 'name'   => 'ст.', 'status' => 1],
            ['level'  => 65, 'name'   => 'стр.', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер.', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. ГСК', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. ДНО', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. ДНП', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. ДНТ', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. ДПК', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. ОНО', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. ОНП', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. ОНТ', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. ОПК', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. СНО', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. СНП', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. СНТ', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. СПК', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер. ТСН', 'status' => 1],
            ['level'  => 65, 'name'   => 'тер.ф.х.', 'status' => 1],
            ['level'  => 65, 'name'   => 'туп.', 'status' => 1],
            ['level'  => 65, 'name'   => 'ул.', 'status' => 1],
            ['level'  => 65, 'name'   => 'ус.', 'status' => 1],
            ['level'  => 65, 'name'   => 'ф/х', 'status' => 1],
            ['level'  => 65, 'name'   => 'х.', 'status' => 1],
            ['level'  => 65, 'name'   => 'ш.', 'status' => 1],
            ['level'  => 90, 'name'   => 'гск', 'status' => 1],
            ['level'  => 90, 'name'   => 'днп', 'status' => 1],
            ['level'  => 90, 'name'   => 'местность', 'status' => 1],
            ['level'  => 90, 'name'   => 'мкр', 'status' => 1],
            ['level'  => 90, 'name'   => 'н/п', 'status' => 1],
            ['level'  => 90, 'name'   => 'промзона', 'status' => 1],
            ['level'  => 90, 'name'   => 'сад', 'status' => 1],
            ['level'  => 90, 'name'   => 'снт', 'status' => 1],
            ['level'  => 90, 'name'   => 'тер', 'status' => 1],
            ['level'  => 90, 'name'   => 'ф/х', 'status' => 1],
            ['level'  => 91, 'name'   => 'а/я', 'status' => 1],
            ['level'  => 91, 'name'   => 'аллея', 'status' => 1],
            ['level'  => 91, 'name'   => 'б-р', 'status' => 1],
            ['level'  => 91, 'name'   => 'въезд', 'status' => 1],
            ['level'  => 91, 'name'   => 'городок', 'status' => 1],
            ['level'  => 91, 'name'   => 'гск', 'status' => 1],
            ['level'  => 91, 'name'   => 'дор', 'status' => 1],
            ['level'  => 91, 'name'   => 'зона', 'status' => 1],
            ['level'  => 91, 'name'   => 'кв-л', 'status' => 1],
            ['level'  => 91, 'name'   => 'км', 'status' => 1],
            ['level'  => 91, 'name'   => 'линия', 'status' => 1],
            ['level'  => 91, 'name'   => 'мкр', 'status' => 1],
            ['level'  => 91, 'name'   => 'п/о', 'status' => 1],
            ['level'  => 91, 'name'   => 'парк', 'status' => 1],
            ['level'  => 91, 'name'   => 'пер', 'status' => 1],
            ['level'  => 91, 'name'   => 'переезд', 'status' => 1],
            ['level'  => 91, 'name'   => 'пл', 'status' => 1],
            ['level'  => 91, 'name'   => 'пл-ка', 'status' => 1],
            ['level'  => 91, 'name'   => 'пр-кт', 'status' => 1],
            ['level'  => 91, 'name'   => 'проезд', 'status' => 1],
            ['level'  => 91, 'name'   => 'просека', 'status' => 1],
            ['level'  => 91, 'name'   => 'проулок', 'status' => 1],
            ['level'  => 91, 'name'   => 'ряды', 'status' => 1],
            ['level'  => 91, 'name'   => 'сад', 'status' => 1],
            ['level'  => 91, 'name'   => 'снт', 'status' => 1],
            ['level'  => 91, 'name'   => 'спуск', 'status' => 1],
            ['level'  => 91, 'name'   => 'ст', 'status' => 1],
            ['level'  => 91, 'name'   => 'стр', 'status' => 1],
            ['level'  => 91, 'name'   => 'тер', 'status' => 1],
            ['level'  => 91, 'name'   => 'тракт', 'status' => 1],
            ['level'  => 91, 'name'   => 'туп', 'status' => 1],
            ['level'  => 91, 'name'   => 'ул', 'status' => 1],
            ['level'  => 91, 'name'   => 'уч-к', 'status' => 1],
            ['level'  => 91, 'name'   => 'ш', 'status' => 1],
            ['level'  => 2, 'name'   => 'округ', 'status' => 1]
        ]);
    }
}
